// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOjkiuivVzTddasxvPAs4gPvIXwsR_-D8',
    appId: '1:168011715359:web:952732de0463aafa86562a',
    messagingSenderId: '168011715359',
    projectId: 'autofixer-a6596',
    authDomain: 'autofixer-a6596.firebaseapp.com',
    storageBucket: 'autofixer-a6596.appspot.com',
    measurementId: 'G-TV1CBKBXL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnhWQqFcZT4ImpzA0tJFwwRcjdCdLvAkc',
    appId: '1:168011715359:android:4e271c193e1d1f8886562a',
    messagingSenderId: '168011715359',
    projectId: 'autofixer-a6596',
    storageBucket: 'autofixer-a6596.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeHaIPJ2wnrulGQ2bjOfVoQ-PhGyxqTd8',
    appId: '1:168011715359:ios:9356a3284861941286562a',
    messagingSenderId: '168011715359',
    projectId: 'autofixer-a6596',
    storageBucket: 'autofixer-a6596.appspot.com',
    iosBundleId: 'com.example.aplicacionTaller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeHaIPJ2wnrulGQ2bjOfVoQ-PhGyxqTd8',
    appId: '1:168011715359:ios:9356a3284861941286562a',
    messagingSenderId: '168011715359',
    projectId: 'autofixer-a6596',
    storageBucket: 'autofixer-a6596.appspot.com',
    iosBundleId: 'com.example.aplicacionTaller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOjkiuivVzTddasxvPAs4gPvIXwsR_-D8',
    appId: '1:168011715359:web:1aaa8a59114a636a86562a',
    messagingSenderId: '168011715359',
    projectId: 'autofixer-a6596',
    authDomain: 'autofixer-a6596.firebaseapp.com',
    storageBucket: 'autofixer-a6596.appspot.com',
    measurementId: 'G-8DGQ9FJDE2',
  );

}